---
title: "Start Empowering Your JS Code🔥💹"
seoTitle: ""Handle JavaScript Errors with Try, Catch, Finally""
seoDescription: ""Learn how to effectively handle JavaScript errors using try, catch, and finally statements. Enhance error management in your code. Find out more!""
datePublished: Sun Jul 23 2023 09:43:10 GMT+0000 (Coordinated Universal Time)
cuid: clkf9419a000009kyh6p46uhq
slug: start-empowering-your-js-code
cover: https://cdn.hashnode.com/res/hashnode/image/upload/v1689759125431/8df8503c-7fcc-4b08-8210-380e9ef7cd70.png
tags: interview, software-development, web-development, mern, exceptionhandling

---

Welcome😍 to an interactive journey into the world of JavaScript error handling!

In this blog, we will explore the powerful techniques of using `try, catch, finally, and throw` statements to effectively handle errors in your JavaScript code. Get ready to empower your programming skills and take control of those pesky errors.

**Let's dive in!**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1689755850895/4464684d-540c-420f-a45f-8155b16da067.gif align="center")

Errors are common in programming, and it's crucial to know how to handle them properly.

The try, catch, and finally, blocks are used for error handling. Before diving into these blocks, it's important to understand the types of errors in programming.

By being aware of different error types, we can effectively handle them using the try, catch, and finally blocks.

# Types of Errors😭:

In programming, there are two types of errors:

1. ***Syntax Error:*** Mistakes in code syntax😂, like misspelt keywords or missing characters. These errors are caught during compilation and prevent code execution.
    
2. ***Runtime Error:*** Occur during program execution🫡, also known as exceptions. Examples include calling an invalid function or accessing undefined variables.
    

These errors that occur during runtime are called `exceptions`. Now, let's see how you can handle these exceptions.

> The `try`statement tests a block of code for errors.
> 
> The `catch` statement handles the error that occurs.
> 
> The `throw` statement creates custom errors.
> 
> The `finally` statement executes code after try and catch, regardless of the result.

# **"try...catch" Block💪**

The try-catch statement is used to handle exceptions in JavaScript. Its syntax is:

```javascript
try {
    // Code to be executed
} 
catch(error) {
    // Code to handle the error
}
```

In this structure, the main code is placed inside the `try block`. If an error occurs during the execution of the try block, the `catch` block is triggered. The `catch` block is responsible for handling the error based on the specified catch statements.

If no error occurs, the code inside the `try` block is executed, and the `catch` block is skipped.

# **"Finally" Block👇**

The `finally` block is always used in conjunction with a try-catch statement in JavaScript. It ensures that a specific block of code executes, regardless of whether an exception occurs or not.

The syntax for using the finally block along with `try and catch` is as follows:

```javascript
try {
   // Code where an error may occur
}
catch {
   // Code to handle the error
}
finally {
   // Code that will always execute, regardless of the try and catch blocks
}
```

In this structure, the `try` block contains the code where an error may occur. If an error occurs, the `catch` block is executed to handle the error. Regardless of whether an error occurs or not, the `finally` block is always executed.

The `finally` block is useful for performing cleanup tasks or releasing resources, as it ensures that the specified code is executed even if an exception is thrown or caught.

It's important to note that the catch block and the `finally` block are not required to be used together. At least one of them should be present along with the `try` block.

# **"throw" Block💀**

The `throw` statement in JavaScript allows you to create custom runtime errors.

It interrupts the code flow and transfers control to the nearest `catch` block or caller function with a `catch` block.

The syntax is `throw "custom error text";`

Note: If no `catch` block exists among caller functions, the program will terminate.

```javascript
try {
  // Code where an error may occur
  throw "Custom error message";
} catch (error) {
  // Code to handle the error
  console.log("Error:", error);
} finally {
  // Code that will always execute, regardless of an error
  console.log("Finally block executed");
}
```

```javascript
o/p: Custom error message
```

1. The code is enclosed in a `try block` to identify potential errors during execution.
    
2. The `throw` statement is used within the try block to create a custom error message.
    
3. When the `throw` statement is encountered, and the code flow is immediately transferred to the `catch` block.
    
4. In the `catch` block, the error message is accessed through the error parameter and logged to the console.
    
5. Output: The custom error message **"Custom error message"** will be displayed in the console as a result of the catch block execution.
    

# Takeaways👀

* Error handling handles the runtime errors in the JavaScript
    

* `try` is a keyword that creates the try block. Here the code that can cause an exception is under the wrap under this block.
    
* The`catch`is a keyword that creates the catch block. Additionally, we use it to catch the exception thrown from the try block and execute the code.
    
* `Finally`, the block runs a piece of code always whether there is an exception or not.
    
* The `throw` keyword can create customized exceptions, which can be thrown based on certain conditions.
    

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1689759023034/b7f75634-e2ed-4752-8985-d2a12781afc4.gif align="center")

Thanks for reading!

Happy coding💖 & goodbye!